### ISSUE TITLE
Actor crashed EOFError: end of file reached

### ISSUE THREAD

**Issue by klaaspieter** [alloy/lowdown#18]
I've been able to successfully send notifications in the past but whatever I try at the moment gives me an error. I tried both using the CLI and from `pry`. All result in the same error.

Looking at the stack trace the problem seems to be in openssl, so I tried regenerating my push certificate as well. After doing the certificate dance I'm still getting the error.

I was able to send a push notification with the same certificate/token using [houston].

[houston]: https://github.com/nomad/houston

Logs / stack trace:

```
lowdown --debug --verbose -e "production" -m "Test" -c certificate.pem "[token]"                        
W, [2016-04-21T13:01:51.650617 #98370]  WARN -- : Dangerously suspending task: type=:call, meta={:dangerous_suspend=>true, :method_name=>:initialize}, status=:callwait
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:41:in `response'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:12:in `_send_'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:207:in `new_link'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-pool-0.20.5/lib/celluloid/supervision/container/pool.rb:137:in `__spawn_actor__'
I, [2016-04-21T13:01:51.651909 #98370]  INFO -- : [APNS Connection#0x7ff9bc9ede10] Connecting...
W, [2016-04-21T13:01:51.654349 #98370]  WARN -- : [APNS Connection#0x7ff9bc9ede10] Defer performing request, because the connection has not been established yet.
I, [2016-04-21T13:01:52.212565 #98370]  INFO -- : [APNS Connection#0x7ff9bc9ede10] Connection established.
D, [2016-04-21T13:01:52.212630 #98370] DEBUG -- : [APNS Connection#0x7ff9bc9ede10] Maximum number of streams: 500. Flushing 1 enqueued requests.
D, [2016-04-21T13:01:52.212854 #98370] DEBUG -- : [APNS Connection#0x7ff9bc9ede10] [00000000-0000-0000-0000-000000000001] Performing request
E, [2016-04-21T13:01:52.377537 #98370] ERROR -- : Actor crashed!
EOFError: end of file reached
	/Users/klaaspieter/.rubies/ruby-2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:178:in `sysread_nonblock'
	/Users/klaaspieter/.rubies/ruby-2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:178:in `read_nonblock'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:42:in `block in sysread'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:390:in `synchronize'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:40:in `sysread'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:129:in `readpartial'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/lowdown-0.3.1/lib/lowdown/connection.rb:223:in `block in runloop'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/lowdown-0.3.1/lib/lowdown/connection.rb:221:in `loop'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/lowdown-0.3.1/lib/lowdown/connection.rb:221:in `runloop'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
I, [2016-04-21T13:01:52.377761 #98370]  INFO -- : [APNS Connection#0x7ff9bc9ede10] Closing...
D, [2016-04-21T13:01:52.506076 #98370] DEBUG -- : Terminating 6 actors...
W, [2016-04-21T13:01:52.507216 #98370]  WARN -- : Dangerously suspending task: type=:finalizer, meta={:dangerous_suspend=>true, :method_name=>:__shutdown__}, status=:receiving
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:230:in `receive'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:395:in `receive'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:90:in `value'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-pool-0.20.5/lib/celluloid/supervision/container/pool.rb:39:in `block in __shutdown__'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-pool-0.20.5/lib/celluloid/supervision/container/pool.rb:39:in `each'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-pool-0.20.5/lib/celluloid/supervision/container/pool.rb:39:in `__shutdown__'
D, [2016-04-21T13:01:52.507285 #98370] DEBUG -- : Discarded message (mailbox is dead): #<Celluloid::TerminationRequest:0x007ff9bd9a0650>
W, [2016-04-21T13:01:52.507369 #98370]  WARN -- : Terminating task: type=:finalizer, meta={:dangerous_suspend=>true, :method_name=>:__shutdown__}, status=:receiving
	Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.
D, [2016-04-21T13:01:52.507541 #98370] DEBUG -- : Discarded message (mailbox is dead): #<Celluloid::ExitEvent:0x007ff9bd9825d8>
D, [2016-04-21T13:01:52.507600 #98370] DEBUG -- : Discarded message (mailbox is dead): #<Celluloid::TerminationRequest:0x007ff9bd9a0678>
D, [2016-04-21T13:01:52.507742 #98370] DEBUG -- : Discarded message (mailbox is dead): #<Celluloid::ExitEvent:0x007ff9bd982bf0>
D, [2016-04-21T13:01:52.507786 #98370] DEBUG -- : Discarded message (mailbox is dead): #<Celluloid::ExitEvent:0x007ff9bd982e20>
D, [2016-04-21T13:01:52.508087 #98370] DEBUG -- : Discarded message (mailbox is dead): #<Celluloid::Call::Sync:0x007ff9bd981ea8>
D, [2016-04-21T13:01:52.508162 #98370] DEBUG -- : Discarded message (mailbox is dead): #<Celluloid::Future::Result:0x007ff9bd97b800>
/Users/klaaspieter/.rubies/ruby-2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:178:in `sysread_nonblock': end of file reached (EOFError)
	from /Users/klaaspieter/.rubies/ruby-2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:178:in `read_nonblock'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:42:in `block in sysread'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:390:in `synchronize'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:40:in `sysread'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:129:in `readpartial'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/lowdown-0.3.1/lib/lowdown/connection.rb:223:in `block in runloop'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/lowdown-0.3.1/lib/lowdown/connection.rb:221:in `loop'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/lowdown-0.3.1/lib/lowdown/connection.rb:221:in `runloop'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	from /Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by alloy** [comment]
Probably a duplicate of #14, updating to lowdown 0.3.2 should fix it.

**Comment by klaaspieter** [comment]
It appears that way. Now I'm stuck with 400 Bad Device Token.
