### ISSUE TITLE
400 (Bad request): BadDeviceToken

### ISSUE THREAD

**Issue by klaaspieter** [alloy/lowdown#19]
After resolving #18 by updating I'm stuck with 400 (Bad request): BadDeviceToken. At first I was sure the problem was on my end so I regenerated the certificate (again), regenerated the provisioning profile and obtained a new device token. After which I was still getting the same error.

I tried [houston] and it was able to send a push notification with the same certificate/token.

[houston]: https://github.com/nomad/houston

lowdown output:

```
lowdown --verbose --debug -m "Test" -c ~/Desktop/courier.pem "TOKEN"                                      
W, [2016-04-21T14:39:16.713108 #1547]  WARN -- : Dangerously suspending task: type=:call, meta={:dangerous_suspend=>true, :method_name=>:initialize}, status=:callwait
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:41:in `response'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:12:in `_send_'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:207:in `new_link'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-pool-0.20.5/lib/celluloid/supervision/container/pool.rb:137:in `__spawn_actor__'
I, [2016-04-21T14:39:16.714120 #1547]  INFO -- : [APNS Connection#0x7fa2fa9459b8] Connecting...
W, [2016-04-21T14:39:16.716218 #1547]  WARN -- : [APNS Connection#0x7fa2fa9459b8] Defer performing request, because the connection has not been established yet.
I, [2016-04-21T14:39:17.227672 #1547]  INFO -- : [APNS Connection#0x7fa2fa9459b8] Connection established.
A, [2016-04-21T14:39:17.593979 #1547]   ANY -- : [f0281baf4cab20443e9a060ccd866f1b5831d3b35f042a04b70a885a361f13b5 #1] 400 (Bad request): BadDeviceToken
I, [2016-04-21T14:39:17.595159 #1547]  INFO -- : [APNS Connection#0x7fa2fa9459b8] Closing...
W, [2016-04-21T14:39:17.725619 #1547]  WARN -- : Dangerously suspending task: type=:finalizer, meta={:dangerous_suspend=>true, :method_name=>:__shutdown__}, status=:receiving
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:230:in `receive'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:395:in `receive'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:90:in `value'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-pool-0.20.5/lib/celluloid/supervision/container/pool.rb:39:in `block in __shutdown__'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-pool-0.20.5/lib/celluloid/supervision/container/pool.rb:39:in `each'
	/Users/klaaspieter/.gem/ruby/2.3.0/gems/celluloid-pool-0.20.5/lib/celluloid/supervision/container/pool.rb:39:in `__shutdown__'
W, [2016-04-21T14:39:17.725756 #1547]  WARN -- : Terminating task: type=:finalizer, meta={:dangerous_suspend=>true, :method_name=>:__shutdown__}, status=:receiving
	Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.
```

**Comment by klaaspieter** [comment]
I wish I could debug this further because it appears the 400 response _is_ coming from APNS. Unfortunately AFAIK houston doesn't provide any more information. The only thing I can think of is that that makes a difference is houston using the old APNS API.

**Comment by alloy** [comment]
Is that token obtained from a dev build of your app? If so, you might need to specify `-e development`.

**Comment by klaaspieter** [comment]
I knew it was going to be something stupid like that.

Any idea why this worked before without having to specify the environment?

**Comment by alloy** [comment]
You probably didn’t have a ‘Universal’ certificate before, meaning that it was tied to a specific environment. When given a Universal certificate, lowdown opts for production > development if possible, my thinking there was that people would often be using this against betas of their app.

https://github.com/alloy/lowdown/blob/8adcc07e75a350fb03ff50d08c07211806164c43/bin/lowdown#L104-L108

But I’m now thinking that it’s more likely that people are using the CLI against a dev build. Mind PRing that?

**Comment by klaaspieter** [comment]
I would, but...

```
./bin/lowdown -m "Test" -c ~/Desktop/courier.pem "TOKEN" -e "development"
W, [2016-04-21T15:53:50.567654 #4551]  WARN -- : [APNS Connection#0x7fc3ab9e6d28] Defer performing request, because the connection has not been established yet.
A, [2016-04-21T15:53:51.146528 #4551]   ANY -- : [f0281baf4cab20443e9a060ccd866f1b5831d3b35f042a04b70a885a361f13b5 #1] 400 (Bad request): BadDeviceToken
```
```
./bin/lowdown -m "Test" -c ~/Desktop/courier.pem "TOKEN" -e "production"
W, [2016-04-21T15:53:56.534742 #4570]  WARN -- : [APNS Connection#0x7f976a97ad70] Defer performing request, because the connection has not been established yet.
A, [2016-04-21T15:53:57.438929 #4570]   ANY -- : [f0281baf4cab20443e9a060ccd866f1b5831d3b35f042a04b70a885a361f13b5 #1] 200 (Success)
```

Same (development) build, same certificate.

**Comment by alloy** [comment]
I’m not sure I follow completely, are you saying that previously you specified `-e "development"` and now it only works with `-e "production"`?

**Comment by klaaspieter** [comment]
Yeah. I followed your suggestion and specified `-e "development"`. Per your suggestion I changed the binary to use `development` as the default, but then I got 400 Bad Token again. At first I assumed I didn't make the change correctly so tried to run with `-e "development"` which gave me the same result.

Then I tried `-e production` which now sends the push notification as expected.
